# remember to create under ~/.okta_aws.toml - https://github.com/chef/okta_aws
[general]
username = "clavery"
okta_server = "chef.okta.com"

[aliases]
spt = "chef-support"

[chef-support]
session_duration = 3600