apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep-ngx
  name: dep-ngx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep-ngx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep-ngx
    spec:
      containers:
      - image: nginx:1.13.8
        name: nginx
        resources: {}
status: {}
