apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:1.12.2
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: 4-pvc
          mountPath: /usr/share/nginx/html
      volumes:
      - name: 4-pvc
        persistentVolumeClaim:
          claimName: 4-pvc
