apiVersion: v1
kind: Pod
metadata:
  name: upnready
  labels:
    app: upnready
spec:
  containers:
  - name: upnready
    image: nginx
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
