apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    pod-template-hash: 6799fc88d8
  name: nginx-6799fc88d8-v8c4n
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: nginx
    pod-template-hash: 6799fc88d8
status:
  loadBalancer: {}
